"""AI Service for task analysis."""

import re
from datetime import datetime
from typing import Optional, List, Any
from groq import Groq
from app.config import settings


class AIService:
    """Service for AI-powered task analysis."""

    def __init__(self):
        self.client: Optional[Groq] = None
        if settings.GROQ_API_KEY:
            self.client = Groq(api_key=settings.GROQ_API_KEY)

    def _get_client(self) -> Groq:
        """Get or initialize Groq client."""
        if not self.client:
            raise ValueError("GROQ_API_KEY not configured")
        return self.client

    def _create_analysis_prompt(self, task: Any) -> str:
        """Create prompt for task analysis."""
        return f"""Analyze the following task and provide a comprehensive report in markdown format.

Task Information:
- Title: {task.title}
- Description: {task.description or "No description provided"}
- Priority: {task.priority}
- Status: {task.status}
- Tags: {", ".join(task.tags) if task.tags else "None"}
- Due Date: {task.due_date.strftime("%Y-%m-%d") if task.due_date else "Not set"}
- Estimated Hours: {task.estimated_hours if task.estimated_hours else "Not estimated"}

Please provide a detailed analysis with the following sections:
1. **Task Summary** - Brief overview of what needs to be done
2. **Complexity Assessment** - How complex is this task? (Low/Medium/High)
3. **Key Objectives** - Main goals that need to be achieved
4. **Recommended Approach** - Suggested methodology or strategy
5. **Potential Challenges** - Obstacles that might arise
6. **Dependencies** - What might this task depend on?
7. **Next Steps** - Concrete actions to start working on this task
8. **Success Criteria** - How to know when the task is complete

Format the response in clean markdown without any introductory text."""

    async def analyze_task(self, task: Any) -> str:
        """Analyze task and generate markdown report."""
        client = self._get_client()

        prompt = self._create_analysis_prompt(task)

        try:
            response = client.chat.completions.create(
                model="llama3-8b-8192",
                messages=[
                    {
                        "role": "system",
                        "content": "You are an expert project manager and task analyst. Provide detailed, actionable task analysis in markdown format.",
                    },
                    {"role": "user", "content": prompt},
                ],
                temperature=0.7,
                max_tokens=2048,
                timeout=settings.AI_TIMEOUT,
            )

            content = response.choices[0].message.content
            # Clean up the response
            content = content.strip()
            if content.startswith("```markdown"):
                content = content[11:]
            if content.startswith("```"):
                content = content[3:]
            if content.endswith("```"):
                content = content[:-3]

            return content.strip()

        except Exception as e:
            raise Exception(f"AI analysis failed: {str(e)}")

    async def generate_task_report(self, task: Any) -> str:
        """Generate complete markdown report for task."""
        analysis = await self.analyze_task(task)

        # Create structured markdown document
        report = f"""# Task Analysis Report

## 📋 Task Information

| Field | Value |
|-------|-------|
| **Title** | {task.title} |
| **Priority** | {task.priority.upper()} |
| **Status** | {task.status.replace("_", " ").title()} |
| **Tags** | {", ".join(task.tags) if task.tags else "None"} |
| **Due Date** | {task.due_date.strftime("%Y-%m-%d") if task.due_date else "Not set"} |
| **Estimated Hours** | {task.estimated_hours if task.estimated_hours else "Not estimated"} |

---

{analysis}

---

## 📝 Original Description

{task.description or "*No description provided*"}

---

*Generated by AI on {task.created_at.strftime("%Y-%m-%d %H:%M")}*
"""

        return report


# Global instance
ai_service = AIService()
